### ISSUE TITLE
Application works offline

### ISSUE THREAD

**Issue by HubertBalcerzak** [Starchasers/up#78]
Frontend loads from cache when user has no internet/backed server is turned off. Makes no sense, since every feature of the website requires connection with backend.

**Comment by Kuboczoch** [comment]
It's a feature because we are not expecting from user to download the whole website every time, even if he has no internet connection or server is offline.
We could have a new feature to display if he has an internet connection if that helps.

**Comment by Kuboczoch** [comment]
After discussing with @HubertBalcerzak, I have come to the conclusion that there is no possible use case to this issue, it only refers to the dev version.

**Comment by Kuboczoch** [comment]
In 99% of cases, we should display this site, I would prefer to just display another error message with "no internet connection".
